-- MySQL Script generated by MySQL Workbench
-- Tue Jun 30 11:20:51 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema coursedb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coursedb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coursedb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `coursedb` ;

-- -----------------------------------------------------
-- Table `coursedb`.`authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`authority` (
  `id` BIGINT(20) NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`type_of_company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`type_of_company` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`company` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `adress` LONGTEXT NOT NULL,
  `category` VARCHAR(80) NOT NULL,
  `cuil` BIGINT(20) NOT NULL,
  `foundation_year` TINYBLOB NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `phone` INT(11) NOT NULL,
  `type_of_company_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKqh4c3nwocr5weu07se4ih6c94` (`type_of_company_id` ASC) VISIBLE,
  CONSTRAINT `FKqh4c3nwocr5weu07se4ih6c94`
    FOREIGN KEY (`type_of_company_id`)
    REFERENCES `coursedb`.`type_of_company` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`course` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `available` TINYINT(1) NOT NULL,
  `category` VARCHAR(100) NOT NULL,
  `cost` DOUBLE NOT NULL,
  `description` LONGTEXT NOT NULL,
  `direct_award` INT(11) NOT NULL,
  `modality` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `quota` INT(11) NOT NULL,
  `scolarship` INT(11) NOT NULL,
  `scolarship_accountant` INT(11) NOT NULL,
  `workload` INT(11) NOT NULL,
  `company_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKfn27utlhh5j98bad3o65fkts9` (`company_id` ASC) VISIBLE,
  CONSTRAINT `FKfn27utlhh5j98bad3o65fkts9`
    FOREIGN KEY (`company_id`)
    REFERENCES `coursedb`.`company` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`hibernate_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`hibernate_sequence` (
  `next_val` BIGINT(20) NULL DEFAULT NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`manager`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`manager` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(200) NOT NULL,
  `identification` INT(11) NOT NULL,
  `identification_type` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `position` VARCHAR(100) NOT NULL,
  `company_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_8de9hi8pak341xbo79qur7l36` (`company_id` ASC) VISIBLE,
  CONSTRAINT `FKfm5bxgko0lhvytyoqjv1ws3p1`
    FOREIGN KEY (`company_id`)
    REFERENCES `coursedb`.`company` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`student` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `adress` VARCHAR(200) NOT NULL,
  `birthdate` DATE NOT NULL,
  `gender` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`socio_economic_study`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`socio_economic_study` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `amount_of_incomes` DOUBLE NULL DEFAULT NULL,
  `family_in_charge` TINYINT(1) NOT NULL,
  `incomes` TINYINT(1) NOT NULL,
  `numbers_of_family_in_charge` INT(11) NULL DEFAULT NULL,
  `study` TINYINT(1) NOT NULL,
  `work` TINYINT(1) NOT NULL,
  `student_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKa9kei2p2mdtpbtvg840bnlome` (`student_id` ASC) VISIBLE,
  CONSTRAINT `FKa9kei2p2mdtpbtvg840bnlome`
    FOREIGN KEY (`student_id`)
    REFERENCES `coursedb`.`student` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`student_has_course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`student_has_course` (
  `approval_status` TINYINT(1) NULL DEFAULT NULL,
  `direct_award` TINYINT(1) NOT NULL,
  `finalized` TINYINT(1) NULL DEFAULT NULL,
  `course_id` BIGINT(20) NOT NULL,
  `student_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`course_id`, `student_id`),
  INDEX `FKklap8xn59s26dk1qfvhjcubxm` (`student_id` ASC) VISIBLE,
  CONSTRAINT `FKgb4xaicajmi6cxkg8nn954pqb`
    FOREIGN KEY (`course_id`)
    REFERENCES `coursedb`.`course` (`id`),
  CONSTRAINT `FKklap8xn59s26dk1qfvhjcubxm`
    FOREIGN KEY (`student_id`)
    REFERENCES `coursedb`.`student` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`user` (
  `id` BIGINT(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `enabled` BIT(1) NOT NULL,
  `firstName` VARCHAR(50) NOT NULL,
  `lastName` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_jreodf78a7pl5qidfh43axdfb` (`username` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `coursedb`.`user_has_authority`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `coursedb`.`user_has_authority` (
  `User_id` BIGINT(20) NOT NULL,
  `Authority_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`User_id`, `Authority_id`),
  INDEX `FK6l5s4eym5u3gy50phev6atn5u` (`Authority_id` ASC) VISIBLE,
  CONSTRAINT `FK6l5s4eym5u3gy50phev6atn5u`
    FOREIGN KEY (`Authority_id`)
    REFERENCES `coursedb`.`authority` (`id`),
  CONSTRAINT `FKsovponbrvjn41ta1k8fpwr0ka`
    FOREIGN KEY (`User_id`)
    REFERENCES `coursedb`.`user` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
